### PR TITLE
upgrade Qiskit

### PR DESCRIPTION
**Pull request by pandaman64**
Since Qiskit 0.6.0 changed the structure of circuit JSON, some tweaks are needed.
https://github.com/Qiskit/qiskit-terra/commit/ddc0cc9b06d3c7cb95fe99c9892187bb24f74232#diff-f89dd837f98e308f1e8655c2cb1c39ff

### CODE REVIEW

**Comment by nelimee** [comment]
You are right! Thanks!
I will review a little bit the code, make some tests to be sure we don't miss anything, and then merge.

**Comment by nelimee** [comment]
The testing is more tedious than expected. I will update the tests and come back to merge.
One way of improvement would be to change also the loop-variable names:
```py
# Before
for operation in json_circuit['operations']:
# What you have done
for operation in json_circuit['instructions']:
# Improvement?
for instructions in json_circuit['instructions']:
```

**Comment by pandaman64** [comment]
I just grepped all occurrences of `operation`.

**Review by nelimee — APPROVED** [review]
Fine for me! I merge and I will update the tests when possible :) Thanks for your contribution!

**Pull request merged**
